openapi: 3.0.1
info:
  title: payment
  description: API Definition of payment
  version: 1.0.0
servers:
- url: http://localhost:8290/payment
paths:
  /card:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /mobile:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /getMobilePin/{mobile}:
    get:
      parameters:
      - name: mobile
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
